services:
  - type: web
    name: r6xinspector-backend
    runtime: python
    repo: https://github.com/xotiic4201/bot-hosting-b
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:backend  # Changed to backend.py with gunicorn
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
