services:
  - type: web
    name: discord-bot-hoster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
